spring.profiles.active=dev
spring.config.import=optional:classpath:application-dev.properties

server.port=8000
server.servlet.context-path=/api
spring.datasource.url=${SPRING_DATABASE_URL}
spring.datasource.username=${SPRING_DATABASE_USERNAME}
spring.datasource.password=${SPRING_DATABASE_PASSWORD}

jwt.refreshKey=${SPRING_SECRET_REFRESH_KEY}
jwt.accessKey=${SPRING_SECRET_ACCESS_KEY}
jwt.durationRefresh=${DURATION_TIME_REFRESH}
jwt.durationAccess= ${DURATION_TIME_ACCESS}
jwt.chronoRefresh=${CHRONO_REFRESH}
jwt.chronoAccess=${CHRONO_ACCESS}
jwt.cookieRefresh=${COOKIE_REFRESH}
jwt.cookieAccess=${COOKIE_ACCESS}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
